import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FT Tech Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Nigel Pelvin / FT</h1>

        <p className={styles.description}>
          Click &quot;View Project&quot; to see tech test in action.
        </p>

        <div className={styles.grid}>
          <Link href="ft/">
            <a className={styles.card}>
              <h2>View Project &rarr;</h2>
              <p>Click to view project</p>
            </a>
          </Link>

            <a
              href="https://github.com/nPelvin/nextJS/blob/main/README.md"
              className={styles.card}
            >
              <h2>ReadMe &rarr;</h2>
              <p>View readme</p>
            </a>

          <a
            href="https://github.com/nPelvin/nextJS"
            className={styles.card}
          >
            <h2>GitHub &rarr;</h2>
            <p>View repository</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="http://lovestocode.com" target="_blank" rel="noreferrer">
          Created by Nige @ LovesToCode.com
        </a>
      </footer>
    </div>
  );
}
